THN.Web.Cookbook/Controllers/CookbookMVCController.cs
using System;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using THN.Web.Cookbook.Models;

namespace THN.Web.Cookbook.Controllers
{
    public class CookbookMVCController : Controller
    {
        private ICookbookContext db = new CookbookContext();

        public CookbookMVCController() { }

        public CookbookMVCController(ICookbookContext context)
        {
            db = context;
        }

        // GET: CookbookMVC
        public ActionResult Index(string sortOrder, string currentFilter, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.CategorySortParm = sortOrder == "category" ? "categorgy_desc" : "category";

            ViewBag.CurrentFilter = searchString;

            var recipes = from r in db.Recipes select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                recipes = recipes.Where(r => r.Title.Contains(searchString) || r.Category.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "title_desc":
                    recipes = recipes.OrderByDescending(r => r.Title);
                    break;
                case "category":
                    recipes = recipes.OrderBy(r => r.Category.ToString());
                    break;
                case "category_desc":
                    recipes = recipes.OrderByDescending(r => r.Category.ToString());
                    break;
                default:
                    recipes = recipes.OrderBy(r => r.Title);
                    break;
            }

            return View("Index", recipes);
        }

        // GET: CookbookMVC/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            recipe.Notes = db.RecipeNotes.Where(n => n.RecipeFk == id).ToList();
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        // GET: CookbookMVC/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CookbookMVC/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecipeId,Source,Instructions,RowVersion,Title,Category")] Recipe recipe)
        {
            if (ModelState.IsValid )
            {
                db.Recipes.Add(recipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Create",recipe);
        }

        // GET: CookbookMVC/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View("Edit",recipe);
        }

        // POST: CookbookMVC/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecipeId,Source,Instructions,RowVersion,Title,Category")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(recipe).State = EntityState.Modified;
                db.SetModified(typeof(Recipe));
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Edit", recipe);
        }

        // GET: CookbookMVC/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View("Delete",recipe);
        }

        // POST: CookbookMVC/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

THN.Web.Cookbook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("THN.v5", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cookbook Angular4 SPA", "CookbookAngular4", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cookbook TS SPA", "CookbookTs", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cookbook JS SPA", "CookbookJs", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cookbook MVC", "Index", "CookbookMVC", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Steve Trofemuk</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

THN.Web.Cookbook/Views/Shared/_NotesList.cshtml
@model IEnumerable<THN.Web.Cookbook.Models.RecipeNote>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Notes</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoteType)
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @foreach (var value in EnumHelper<NoteTypeEnum>.GetValues(NoteTypeEnum.NoteOnly))
            {
                if (value == item.NoteType)
                {
                    var description = EnumHelper<NoteTypeEnum>.GetDisplayValue(value);
                    @Html.DisplayFor(e => description);
                    break;
                }
            }
        </td>
    </tr>
    }
</table>